## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'lo'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":lo, "groupName":"wishful_contiki"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0','lowpan1']
        kwargs : {'GitarConfig' : './config/localhost/gitar.ini','SupportedInterfaces' : ['lowpan0','lowpan1'],'ControlExtensions' : {'taisc' : './taisc_control_extensions.csv', 'rime' : './rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0','lowpan1']
        kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}, 'SupportedInterfaces' : ['lowpan0','lowpan1']}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0','lowpan1']
        kwargs : {'SupportedInterfaces' : ['lowpan0','lowpan1']}
