## WiSHFUL global control program config file

controller:
    name: "contiki_global_control"
    info: "Example Contiki global control program"
    dl: "tcp://127.0.0.1:8990"
    ul: "tcp://127.0.0.1:8989"

modules: {}
