## WiSHFUL Agent config file

agent_config:
  name: 'Local_WiFi_Controller'
  info: 'CPs and modules on single node'
  type: 'local'
  iface: 'lo'

controllers:
  myController:
      file : local_control_app.py
      class_name : MyController
      kwargs : {}

modules:
  wifi:
      module : wishful_module_wifi
      class_name : WifiModule
      devices : ['phy0']
