## WiSHFUL Agent config file

agent_config:
  name: 'Local_Controller'
  info: 'local controller example for testing hybrid MAC from wifi ath module'
  type: 'local'
  iface: 'lo'

controllers:
  myController:
      file : local_hmax_ex.py
      class_name : HybridMACLocalController
      kwargs : {}

modules:
  wifiath:
      module : wishful_module_wifi_ath
      class_name : Ath9kModule
      devices : ['phy0']