## WiSHFUL Agent config file

agent_config:
  name: 'HC node'
  info: 'filter runs on local node'
  type: 'slave'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      devices : ['phy0']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule
