## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'lo'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":eth0, "groupName":"wishful_contiki"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0']
        kwargs :
            GitarConfig : './config/localhost/gitar.ini'
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : './config/protocol_connectors/gitar_ctrl_attributes.csv'
            ControlFunctions : './config/protocol_connectors/gitar_ctrl_functions.csv'
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0']
        kwargs :
            RadioPrograms : {"CSMA":0,"TDMA":2,"TSCH":1}
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : './config/protocol_connectors/taisc_ctrl_attributes.csv'
            ControlFunctions : './config/protocol_connectors/taisc_ctrl_functions.csv'
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0']
        kwargs :
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : './config/protocol_connectors/rime_ctrl_attributes.csv'
            ControlFunctions : './config/protocol_connectors/rime_ctrl_functions.csv'
